<?php

namespace App\Enums;

enum CountryEnum: string
{
    case Afghanistan = "AF";
    case Albania = "AL";
    case Algeria = "DZ";
    case AmericanSamoa = "AS";
    case Andorra = "AD";
    case Angola = "AO";
    case Anguilla = "AI";
    case Antarctica = "AQ";
    case AntiguaAndBarbuda = "AG";
    case Argentina = "AR";
    case Armenia = "AM";
    case Aruba = "AW";
    case Australia = "AU";
    case Austria = "AT";
    case Azerbaijan = "AZ";
    case Bahamas = "BS";
    case Bahrain = "BH";
    case Bangladesh = "BD";
    case Barbados = "BB";
    case Belarus = "BY";
    case Belgium = "BE";
    case Belize = "BZ";
    case Benin = "BJ";
    case Bermuda = "BM";
    case Bhutan = "BT";
    case Bolivia = "BO";
    case BosniaAndHerzegovina = "BA";
    case Botswana = "BW";
    case BouvetIsland = "BV";
    case Brazil = "BR";
    case BritishIndianOceanTerritory = "IO";
    case BruneiDarussalam = "BN";
    case Bulgaria = "BG";
    case BurkinaFaso = "BF";
    case Burundi = "BI";
    case Cambodia = "KH";
    case Cameroon = "CM";
    case Canada = "CA";
    case CapeVerde = "CV";
    case CaymanIslands = "KY";
    case CentralAfricanRepublic = "CF";
    case Chad = "TD";
    case Chile = "CL";
    case China = "CN";
    case ChristmasIsland = "CX";
    case CocosKeelingIslands = "CC";
    case Colombia = "CO";
    case Comoros = "KM";
    case Congo = "CG";
    case CongoTheDemocraticRepublicOfThe = "CD";
    case CookIslands = "CK";
    case CostaRica = "CR";
    case CoteDIvoire = "CI";
    case Croatia = "HR";
    case Cuba = "CU";
    case Cyprus = "CY";
    case CzechRepublic = "CZ";
    case Denmark = "DK";
    case Djibouti = "DJ";
    case Dominica = "DM";
    case DominicanRepublic = "DO";
    case Ecuador = "EC";
    case Egypt = "EG";
    case ElSalvador = "SV";
    case EquatorialGuinea = "GQ";
    case Eritrea = "ER";
    case Estonia = "EE";
    case Ethiopia = "ET";
    case FalklandIslandsMalvinas = "FK";
    case FaroeIslands = "FO";
    case Fiji = "FJ";
    case Finland = "FI";
    case France = "FR";
    case FrenchGuiana = "GF";
    case FrenchPolynesia = "PF";
    case FrenchSouthernTerritories = "TF";
    case Gabon = "GA";
    case Gambia = "GM";
    case Georgia = "GE";
    case Germany = "DE";
    case Ghana = "GH";
    case Gibraltar = "GI";
    case Greece = "GR";
    case Greenland = "GL";
    case Grenada = "GD";
    case Guadeloupe = "GP";
    case Guam = "GU";
    case Guatemala = "GT";
    case Guinea = "GN";
    case GuineaBissau = "GW";
    case Guyana = "GY";
    case Haiti = "HT";
    case HeardIslandAndMcdonaldIslands = "HM";
    case HolySeeVaticanCityState = "VA";
    case Honduras = "HN";
    case HongKong = "HK";
    case Hungary = "HU";
    case Iceland = "IS";
    case India = "IN";
    case Indonesia = "ID";
    case IranIslamicRepublicOf = "IR";
    case Iraq = "IQ";
    case Ireland = "IE";
    case Israel = "IL";
    case Italy = "IT";
    case Jamaica = "JM";
    case Japan = "JP";
    case Jordan = "JO";
    case Kazakhstan = "KZ";
    case Kenya = "KE";
    case Kiribati = "KI";
    case KoreaDemocraticPeoplesRepublicOf = "KP";
    case KoreaRepublicOf = "KR";
    case Kuwait = "KW";
    case Kyrgyzstan = "KG";
    case LaoPeoplesDemocraticRepublic = "LA";
    case Latvia = "LV";
    case Lebanon = "LB";
    case Lesotho = "LS";
    case Liberia = "LR";
    case LibyanArabJamahiriya = "LY";
    case Liechtenstein = "LI";
    case Lithuania = "LT";
    case Luxembourg = "LU";
    case Macao = "MO";
    case MacedoniaTheFormerYugoslavRepublicOf = "MK";
    case Madagascar = "MG";
    case Malawi = "MW";
    case Malaysia = "MY";
    case Maldives = "MV";
    case Mali = "ML";
    case Malta = "MT";
    case MarshallIslands = "MH";
    case Martinique = "MQ";
    case Mauritania = "MR";
    case Mauritius = "MU";
    case Mayotte = "YT";
    case Mexico = "MX";
    case MicronesiaFederatedStatesOf = "FM";
    case MoldovaRepublicOf = "MD";
    case Monaco = "MC";
    case Mongolia = "MN";
    case Montserrat = "MS";
    case Morocco = "MA";
    case Mozambique = "MZ";
    case Myanmar = "MM";
    case Namibia = "NA";
    case Nauru = "NR";
    case Nepal = "NP";
    case Netherlands = "NL";
    case NetherlandsAntilles = "AN";
    case NewCaledonia = "NC";
    case NewZealand = "NZ";
    case Nicaragua = "NI";
    case Niger = "NE";
    case Nigeria = "NG";
    case Niue = "NU";
    case NorfolkIsland = "NF";
    case NorthernMarianaIslands = "MP";
    case Norway = "NO";
    case Oman = "OM";
    case Pakistan = "PK";
    case Palau = "PW";
    case PalestinianTerritoryOccupied = "PS";
    case Panama = "PA";
    case PapuaNewGuinea = "PG";
    case Paraguay = "PY";
    case Peru = "PE";
    case Philippines = "PH";
    case Pitcairn = "PN";
    case Poland = "PL";
    case Portugal = "PT";
    case PuertoRico = "PR";
    case Qatar = "QA";
    case Reunion = "RE";
    case Romania = "RO";
    case RussianFederation = "RU";
    case Rwanda = "RW";
    case SaintHelena = "SH";
    case SaintKittsAndNevis = "KN";
    case SaintLucia = "LC";
    case SaintPierreAndMiquelon = "PM";
    case SaintVincentAndTheGrenadines = "VC";
    case Samoa = "WS";
    case SanMarino = "SM";
    case SaoTomeandPrincipe = "ST";
    case SaudiArabia = "SA";
    case Senegal = "SN";
    case SerbiaAndMontenegro = "CS";
    case Seychelles = "SC";
    case SierraLeone = "SL";
    case Singapore = "SG";
    case Slovakia = "SK";
    case Slovenia = "SI";
    case SolomonIslands = "SB";
    case Somalia = "SO";
    case SouthAfrica = "ZA";
    case SouthGeorgiaAndTheSouthSandwichIslands = "GS";
    case Spain = "ES";
    case SriLanka = "LK";
    case Sudan = "SD";
    case Suriname = "SR";
    case SvalbardAndJanMayen = "SJ";
    case Swaziland = "SZ";
    case Sweden = "SE";
    case Switzerland = "CH";
    case SyrianArabRepublic = "SY";
    case TaiwanProvinceOfChina = "TW";
    case Tajikistan = "TJ";
    case TanzaniaUnitedRepublicOf = "TZ";
    case Thailand = "TH";
    case TimorLeste = "TL";
    case Togo = "TG";
    case Tokelau = "TK";
    case Tonga = "TO";
    case TrinidadAndTobago = "TT";
    case Tunisia = "TN";
    case Turkey = "TR";
    case Turkmenistan = "TM";
    case TurksAndCaicosIslands = "TC";
    case Tuvalu = "TV";
    case Uganda = "UG";
    case Ukraine = "UA";
    case UnitedArabEmirates = "AE";
    case UnitedKingdom = "GB";
    case UnitedStates = "US";
    case UnitedStatesMinorOutlyingIslands = "UM";
    case Uruguay = "UY";
    case Uzbekistan = "UZ";
    case Vanuatu = "VU";
    case Venezuela = "VE";
    case VietNam = "VN";
    case VirginIslandsBritish = "VG";
    case VirginIslandsUS = "VI";
    case WallisAndFutuna = "WF";
    case WesternSahara = "EH";
    case Yemen = "YE";
    case Zambia = "ZM";
    case Zimbabwe = "ZW";

    public function getLabel(): string
    {
        return match ($this) {
            self::Afghanistan => "Afghanistan",
            self::Albania => "Albania",
            self::Algeria => "Algeria",
            self::AmericanSamoa => "American Samoa",
            self::Andorra => "Andorra",
            self::Angola => "Angola",
            self::Anguilla => "Anguilla",
            self::Antarctica => "Antarctica",
            self::AntiguaAndBarbuda => "Antigua and Barbuda",
            self::Argentina => "Argentina",
            self::Armenia => "Armenia",
            self::Aruba => "Aruba",
            self::Australia => "Australia",
            self::Austria => "Austria",
            self::Azerbaijan => "Azerbaijan",
            self::Bahamas => "Bahamas",
            self::Bahrain => "Bahrain",
            self::Bangladesh => "Bangladesh",
            self::Barbados => "Barbados",
            self::Belarus => "Belarus",
            self::Belgium => "Belgium",
            self::Belize => "Belize",
            self::Benin => "Benin",
            self::Bermuda => "Bermuda",
            self::Bhutan => "Bhutan",
            self::Bolivia => "Bolivia",
            self::BosniaAndHerzegovina => "Bosnia and Herzegovina",
            self::Botswana => "Botswana",
            self::BouvetIsland => "Bouvet Island",
            self::Brazil => "Brazil",
            self::BritishIndianOceanTerritory => "British Indian Ocean Territory",
            self::BruneiDarussalam => "Brunei Darussalam",
            self::Bulgaria => "Bulgaria",
            self::BurkinaFaso => "Burkina Faso",
            self::Burundi => "Burundi",
            self::Cambodia => "Cambodia",
            self::Cameroon => "Cameroon",
            self::Canada => "Canada",
            self::CapeVerde => "Cape Verde",
            self::CaymanIslands => "Cayman Islands",
            self::CentralAfricanRepublic => "Central African Republic",
            self::Chad => "Chad",
            self::Chile => "Chile",
            self::China => "China",
            self::ChristmasIsland => "Christmas Island",
            self::CocosKeelingIslands => "Cocos (Keeling) Islands",
            self::Colombia => "Colombia",
            self::Comoros => "Comoros",
            self::Congo => "Congo",
            self::CongoTheDemocraticRepublicOfThe => "Congo, the Democratic Republic of the",
            self::CookIslands => "Cook Islands",
            self::CostaRica => "Costa Rica",
            self::CoteDIvoire => "Cote D'Ivoire",
            self::Croatia => "Croatia",
            self::Cuba => "Cuba",
            self::Cyprus => "Cyprus",
            self::CzechRepublic => "Czech Republic",
            self::Denmark => "Denmark",
            self::Djibouti => "Djibouti",
            self::Dominica => "Dominica",
            self::DominicanRepublic => "Dominican Republic",
            self::Ecuador => "Ecuador",
            self::Egypt => "Egypt",
            self::ElSalvador => "El Salvador",
            self::EquatorialGuinea => "Equatorial Guinea",
            self::Eritrea => "Eritrea",
            self::Estonia => "Estonia",
            self::Ethiopia => "Ethiopia",
            self::FalklandIslandsMalvinas => "Falkland Islands (Malvinas)",
            self::FaroeIslands => "Faroe Islands",
            self::Fiji => "Fiji",
            self::Finland => "Finland",
            self::France => "France",
            self::FrenchGuiana => "French Guiana",
            self::FrenchPolynesia => "French Polynesia",
            self::FrenchSouthernTerritories => "French Southern Territories",
            self::Gabon => "Gabon",
            self::Gambia => "Gambia",
            self::Georgia => "Georgia",
            self::Germany => "Germany",
            self::Ghana => "Ghana",
            self::Gibraltar => "Gibraltar",
            self::Greece => "Greece",
            self::Greenland => "Greenland",
            self::Grenada => "Grenada",
            self::Guadeloupe => "Guadeloupe",
            self::Guam => "Guam",
            self::Guatemala => "Guatemala",
            self::Guinea => "Guinea",
            self::Guinea => "Guinea-Bissau",
            self::Guyana => "Guyana",
            self::Haiti => "Haiti",
            self::HeardIslandAndMcdonaldIslands => "Heard Island and Mcdonald Islands",
            self::HolySeeVaticanCityState => "Holy See (Vatican City State)",
            self::Honduras => "Honduras",
            self::HongKong => "Hong Kong",
            self::Hungary => "Hungary",
            self::Iceland => "Iceland",
            self::India => "India",
            self::Indonesia => "Indonesia",
            self::IranIslamicRepublicOf => "Iran, Islamic Republic of",
            self::Iraq => "Iraq",
            self::Ireland => "Ireland",
            self::Israel => "Israel",
            self::Italy => "Italy",
            self::Jamaica => "Jamaica",
            self::Japan => "Japan",
            self::Jordan => "Jordan",
            self::Kazakhstan => "Kazakhstan",
            self::Kenya => "Kenya",
            self::Kiribati => "Kiribati",
            self::KoreaDemocraticPeoplesRepublicOf => "Korea, Democratic People's Republic of",
            self::KoreaRepublicOf => "Korea, Republic of",
            self::Kuwait => "Kuwait",
            self::Kyrgyzstan => "Kyrgyzstan",
            self::LaoPeoplesDemocraticRepublic => "Lao People's Democratic Republic",
            self::Latvia => "Latvia",
            self::Lebanon => "Lebanon",
            self::Lesotho => "Lesotho",
            self::Liberia => "Liberia",
            self::LibyanArabJamahiriya => "Libyan Arab Jamahiriya",
            self::Liechtenstein => "Liechtenstein",
            self::Lithuania => "Lithuania",
            self::Luxembourg => "Luxembourg",
            self::Macao => "Macao",
            self::MacedoniaTheFormerYugoslavRepublicOf => "Macedonia, the Former Yugoslav Republic of",
            self::Madagascar => "Madagascar",
            self::Malawi => "Malawi",
            self::Malaysia => "Malaysia",
            self::Maldives => "Maldives",
            self::Mali => "Mali",
            self::Malta => "Malta",
            self::MarshallIslands => "Marshall Islands",
            self::Martinique => "Martinique",
            self::Mauritania => "Mauritania",
            self::Mauritius => "Mauritius",
            self::Mayotte => "Mayotte",
            self::Mexico => "Mexico",
            self::MicronesiaFederatedStatesOf => "Micronesia, Federated States of",
            self::MoldovaRepublicOf => "Moldova, Republic of",
            self::Monaco => "Monaco",
            self::Mongolia => "Mongolia",
            self::Montserrat => "Montserrat",
            self::Morocco => "Morocco",
            self::Mozambique => "Mozambique",
            self::Myanmar => "Myanmar",
            self::Namibia => "Namibia",
            self::Nauru => "Nauru",
            self::Nepal => "Nepal",
            self::Netherlands => "Netherlands",
            self::NetherlandsAntilles => "Netherlands Antilles",
            self::NewCaledonia => "New Caledonia",
            self::NewZealand => "New Zealand",
            self::Nicaragua => "Nicaragua",
            self::Niger => "Niger",
            self::Nigeria => "Nigeria",
            self::Niue => "Niue",
            self::NorfolkIsland => "Norfolk Island",
            self::NorthernMarianaIslands => "Northern Mariana Islands",
            self::Norway => "Norway",
            self::Oman => "Oman",
            self::Pakistan => "Pakistan",
            self::Palau => "Palau",
            self::PalestinianTerritoryOccupied => "Palestinian Territory, Occupied",
            self::Panama => "Panama",
            self::PapuaNewGuinea => "Papua New Guinea",
            self::Paraguay => "Paraguay",
            self::Peru => "Peru",
            self::Philippines => "Philippines",
            self::Pitcairn => "Pitcairn",
            self::Poland => "Poland",
            self::Portugal => "Portugal",
            self::PuertoRico => "Puerto Rico",
            self::Qatar => "Qatar",
            self::Reunion => "Reunion",
            self::Romania => "Romania",
            self::RussianFederation => "Russian Federation",
            self::Rwanda => "Rwanda",
            self::SaintHelena => "Saint Helena",
            self::SaintKittsAndNevis => "Saint Kitts and Nevis",
            self::SaintLucia => "Saint Lucia",
            self::SaintPierreAndMiquelon => "Saint Pierre and Miquelon",
            self::SaintVincentAndTheGrenadines => "Saint Vincent and the Grenadines",
            self::Samoa => "Samoa",
            self::SanMarino => "San Marino",
            self::SaoTomeandPrincipe => "Sao Tome and Principe",
            self::SaudiArabia => "Saudi Arabia",
            self::Senegal => "Senegal",
            self::SerbiaAndMontenegro => "Serbia and Montenegro",
            self::Seychelles => "Seychelles",
            self::SierraLeone => "Sierra Leone",
            self::Singapore => "Singapore",
            self::Slovakia => "Slovakia",
            self::Slovenia => "Slovenia",
            self::SolomonIslands => "Solomon Islands",
            self::Somalia => "Somalia",
            self::SouthAfrica => "South Africa",
            self::SouthGeorgiaAndTheSouthSandwichIslands => "South Georgia and the South Sandwich Islands",
            self::Spain => "Spain",
            self::SriLanka => "Sri Lanka",
            self::Sudan => "Sudan",
            self::Suriname => "Suriname",
            self::SvalbardAndJanMayen => "Svalbard and Jan Mayen",
            self::Swaziland => "Swaziland",
            self::Sweden => "Sweden",
            self::Switzerland => "Switzerland",
            self::SyrianArabRepublic => "Syrian Arab Republic",
            self::TaiwanProvinceOfChina => "Taiwan, Province of China",
            self::Tajikistan => "Tajikistan",
            self::TanzaniaUnitedRepublicOf => "Tanzania, United Republic of",
            self::Thailand => "Thailand",
            self::TimorLeste => "Timor-Leste",
            self::Togo => "Togo",
            self::Tokelau => "Tokelau",
            self::Tonga => "Tonga",
            self::TrinidadAndTobago => "Trinidad and Tobago",
            self::Tunisia => "Tunisia",
            self::Turkey => "Turkey",
            self::Turkmenistan => "Turkmenistan",
            self::TurksAndCaicosIslands => "Turks and Caicos Islands",
            self::Tuvalu => "Tuvalu",
            self::Uganda => "Uganda",
            self::Ukraine => "Ukraine",
            self::UnitedArabEmirates => "United Arab Emirates",
            self::UnitedKingdom => "United Kingdom",
            self::UnitedStates => "United States",
            self::UnitedStatesMinorOutlyingIslands => "United States Minor Outlying Islands",
            self::Uruguay => "Uruguay",
            self::Uzbekistan => "Uzbekistan",
            self::Vanuatu => "Vanuatu",
            self::Venezuela => "Venezuela",
            self::VietNam => "Viet Nam",
            self::VirginIslandsBritish => "Virgin Islands, British",
            self::VirginIslandsUS => "Virgin Islands, U.s.",
            self::WallisAndFutuna => "Wallis and Futuna",
            self::WesternSahara => "Western Sahara",
            self::Yemen => "Yemen",
            self::Zambia => "Zambia",
            self::Zimbabwe => "Zimbabwe",
        };
    }

    public static function toArray(): array
    {
        return array_column(
            array_map(fn($case) => ['value' => $case->value, 'label' => $case->getLabel()], self::cases()),
            'label',
            'value'
        );
    }
}
